# These are supported funding model platforms

github:
patreon: 
open_collective: 
ko_fi: tinvv
tidelift:
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
